export const PREFIX = '@@merchant/';

/**
 * action types to resolve with action and reducer
 */
export const ASYNC_MERCHANT_INIT = `${PREFIX}ASYNC_MERCHANT_INIT`;
export const HANDLE_NOTIFICATION = `${PREFIX}HANDLE_NOTIFICATION`;
export const GET_SERVICES_SUCCESS = `${PREFIX}GET_SERVICES_SUCCESS`;
export const GET_MERCHANT_PROFILE_SUCCESS = `${PREFIX}GET_MERCHANT_PROFILE_SUCCESS`;
export const SEARCH_MERCHANT_PROFILES_SUCCESS = `${PREFIX}SEARCH_MERCHANT_PROFILES_SUCCESS`;
